name: Run ChatGPT

on:
  push:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.4' # Chọn phiên bản Python tương ứng

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: pip install -r requirements.txt # Nếu bạn có tệp tin requirements.txt, thay thế bằng tên thích hợp

      - name: Run Python script
        run: python stock.py # Thay thế 'your_script.py' bằng tên tệp tin chứa mã nguồn của bạn
        env:
          API_KEY: ${{ secrets.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 }} # Thay thế 'API_KEY' bằng tên biến môi trường bạn sử dụng để lưu trữ API Key
